// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: api/gameserver.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_OBSERVER Role = 0
	Role_ROLE_PLAYER   Role = 1
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_OBSERVER",
		1: "ROLE_PLAYER",
	}
	Role_value = map[string]int32{
		"ROLE_OBSERVER": 0,
		"ROLE_PLAYER":   1,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_gameserver_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_gameserver_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{0}
}

type GameMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Frame int32 `protobuf:"varint,1,opt,name=frame,proto3" json:"frame,omitempty"`
	// Types that are assignable to Msg:
	//
	//	*GameMessage_GameInit
	//	*GameMessage_RoleChange
	//	*GameMessage_Heartbeat
	//	*GameMessage_GameEvent
	Msg isGameMessage_Msg `protobuf_oneof:"msg"`
}

func (x *GameMessage) Reset() {
	*x = GameMessage{}
	mi := &file_api_gameserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMessage) ProtoMessage() {}

func (x *GameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMessage.ProtoReflect.Descriptor instead.
func (*GameMessage) Descriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{0}
}

func (x *GameMessage) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (m *GameMessage) GetMsg() isGameMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *GameMessage) GetGameInit() *GameInit {
	if x, ok := x.GetMsg().(*GameMessage_GameInit); ok {
		return x.GameInit
	}
	return nil
}

func (x *GameMessage) GetRoleChange() *RoleChange {
	if x, ok := x.GetMsg().(*GameMessage_RoleChange); ok {
		return x.RoleChange
	}
	return nil
}

func (x *GameMessage) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetMsg().(*GameMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *GameMessage) GetGameEvent() *GameEvent {
	if x, ok := x.GetMsg().(*GameMessage_GameEvent); ok {
		return x.GameEvent
	}
	return nil
}

type isGameMessage_Msg interface {
	isGameMessage_Msg()
}

type GameMessage_GameInit struct {
	// administrative events
	GameInit *GameInit `protobuf:"bytes,2,opt,name=gameInit,proto3,oneof"`
}

type GameMessage_RoleChange struct {
	RoleChange *RoleChange `protobuf:"bytes,3,opt,name=roleChange,proto3,oneof"`
}

type GameMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type GameMessage_GameEvent struct {
	// game-specific events that the server doesn't parse
	GameEvent *GameEvent `protobuf:"bytes,100,opt,name=gameEvent,proto3,oneof"`
}

func (*GameMessage_GameInit) isGameMessage_Msg() {}

func (*GameMessage_RoleChange) isGameMessage_Msg() {}

func (*GameMessage_Heartbeat) isGameMessage_Msg() {}

func (*GameMessage_GameEvent) isGameMessage_Msg() {}

// used to advance the frame count when nothing else has happened for a while
type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_gameserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{1}
}

type GameInit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seed int32 `protobuf:"varint,1,opt,name=seed,proto3" json:"seed,omitempty"`
}

func (x *GameInit) Reset() {
	*x = GameInit{}
	mi := &file_api_gameserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInit) ProtoMessage() {}

func (x *GameInit) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInit.ProtoReflect.Descriptor instead.
func (*GameInit) Descriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{2}
}

func (x *GameInit) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type RoleChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role Role `protobuf:"varint,1,opt,name=role,proto3,enum=gameserver.Role" json:"role,omitempty"`
}

func (x *RoleChange) Reset() {
	*x = RoleChange{}
	mi := &file_api_gameserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleChange) ProtoMessage() {}

func (x *RoleChange) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleChange.ProtoReflect.Descriptor instead.
func (*RoleChange) Descriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{3}
}

func (x *RoleChange) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_OBSERVER
}

type GameEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_api_gameserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_gameserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_api_gameserver_proto_rawDescGZIP(), []int{4}
}

func (x *GameEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_api_gameserver_proto protoreflect.FileDescriptor

var file_api_gameserver_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x22, 0x86, 0x02, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x69, 0x74,
	0x48, 0x00, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x38, 0x0a, 0x0a,
	0x72, 0x6f, 0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x6c, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x35, 0x0a,
	0x09, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0b, 0x0a, 0x09, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x22, 0x1e, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x22, 0x32, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x1f, 0x0a, 0x09,
	0x47, 0x61, 0x6d, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x2a, 0x2a, 0x0a,
	0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4f, 0x42,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_gameserver_proto_rawDescOnce sync.Once
	file_api_gameserver_proto_rawDescData = file_api_gameserver_proto_rawDesc
)

func file_api_gameserver_proto_rawDescGZIP() []byte {
	file_api_gameserver_proto_rawDescOnce.Do(func() {
		file_api_gameserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_gameserver_proto_rawDescData)
	})
	return file_api_gameserver_proto_rawDescData
}

var file_api_gameserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_gameserver_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_gameserver_proto_goTypes = []any{
	(Role)(0),           // 0: gameserver.Role
	(*GameMessage)(nil), // 1: gameserver.GameMessage
	(*Heartbeat)(nil),   // 2: gameserver.Heartbeat
	(*GameInit)(nil),    // 3: gameserver.GameInit
	(*RoleChange)(nil),  // 4: gameserver.RoleChange
	(*GameEvent)(nil),   // 5: gameserver.GameEvent
}
var file_api_gameserver_proto_depIdxs = []int32{
	3, // 0: gameserver.GameMessage.gameInit:type_name -> gameserver.GameInit
	4, // 1: gameserver.GameMessage.roleChange:type_name -> gameserver.RoleChange
	2, // 2: gameserver.GameMessage.heartbeat:type_name -> gameserver.Heartbeat
	5, // 3: gameserver.GameMessage.gameEvent:type_name -> gameserver.GameEvent
	0, // 4: gameserver.RoleChange.role:type_name -> gameserver.Role
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_gameserver_proto_init() }
func file_api_gameserver_proto_init() {
	if File_api_gameserver_proto != nil {
		return
	}
	file_api_gameserver_proto_msgTypes[0].OneofWrappers = []any{
		(*GameMessage_GameInit)(nil),
		(*GameMessage_RoleChange)(nil),
		(*GameMessage_Heartbeat)(nil),
		(*GameMessage_GameEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_gameserver_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_gameserver_proto_goTypes,
		DependencyIndexes: file_api_gameserver_proto_depIdxs,
		EnumInfos:         file_api_gameserver_proto_enumTypes,
		MessageInfos:      file_api_gameserver_proto_msgTypes,
	}.Build()
	File_api_gameserver_proto = out.File
	file_api_gameserver_proto_rawDesc = nil
	file_api_gameserver_proto_goTypes = nil
	file_api_gameserver_proto_depIdxs = nil
}
